# Generated by Django 2.2.7 on 2019-12-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(default='1E1E', max_length=50)),
                ('thumbnail', models.CharField(default='https://SOME STRING', max_length=150)),
                ('category', models.CharField(default='Others', max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(default='share', max_length=50)),
                ('owner_email', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='RateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(default=5)),
                ('review', models.TextField(default='excellent')),
                ('rate_reviewer', models.CharField(default='1', max_length=50)),
                ('book', models.CharField(default='1', max_length=50)),
                ('books_rr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookapp.Books')),
            ],
            options={
                'db_table': 'ratings_reviews',
            },
        ),
    ]
