# Generated by Django 2.1.7 on 2019-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='purpose',
            field=models.CharField(default='Share', max_length=50),
        ),
    ]
