# Generated by Django 2.2.7 on 2019-11-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratereview',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
    ]
