# Generated by Django 2.2.7 on 2019-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_ratereview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratereview',
            name='ratings',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='ratereview',
            name='review',
            field=models.TextField(),
        ),
    ]
