# Generated by Django 2.2.7 on 2019-11-13 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20191113_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereview',
            name='rate_reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
