# Generated by Django 2.2.7 on 2019-11-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20191113_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereview',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_book', to='bookapp.Books'),
        ),
    ]
