# Generated by Django 2.2.7 on 2019-11-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_auto_20191113_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
